### ISSUE TITLE
Error while deleting users 

### ISSUE THREAD

**Issue by dadoeyad** [awesto/django-shop#222]
I'm getting this error while deleting a user in my project.
```
Traceback (most recent call last):

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1205, in changelist_view
    response = self.response_action(request, queryset=cl.get_query_set(request))

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 960, in response_action
    response = func(self, request, queryset)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/actions.py", line 35, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/util.py", line 109, in get_deleted_objects
    collector.collect(objs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/contrib/admin/util.py", line 160, in collect
    return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 225, in collect
    elif sub_objs:

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __nonzero__
    return type(self).__bool__(self)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/query.py", line 135, in __bool__
    next(iter(self))

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/query.py", line 123, in _result_iter
    self._fill_cache()

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/query.py", line 927, in _fill_cache
    self._result_cache.append(next(self._iter))

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 58, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])

  File "/home/eyad/Envs/through_italy/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)

DatabaseError: relation "addressmodel_address" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "addressmo...
```

I'm not using the address model, it's not in my installed apps and it's not in the DB.
I'm using Django 1.5.1

**Comment by jrief** [comment]
Closed. Please check version 0.9.
