### ISSUE TITLE
MoneyField breaks copy.deepcopy

### ISSUE THREAD

**Issue by rfleschenberg** [awesto/django-shop#340]
With the example shop:
```
>>> import copy
>>> from myshop.models import SmartCard
>>> copy.deepcopy(SmartCard.objects.first())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/decimal.py", line 3639, in __deepcopy__
    return self.__class__(str(self))
  File "/home/rene/django-shop/shop/money/money_maker.py", line 210, in new_money
    raise ValueError(err)
ValueError: Invalid literal for Decimal: '\xe2\x82\xac 3.99'
>>> 
```

**Comment by rfleschenberg** [comment]
I think we should implement `__deepcopy__()` on the class to avoid this problem. There are some notes at the bottom of this page: https://docs.python.org/2/library/copy.html
