### ISSUE TITLE
Cannot edit products in admin

### ISSUE THREAD

**Issue by rfleschenberg** [awesto/django-shop#381]
In my current project, trying to edit a product in the admin raises 500.

We have this code in `shop/money/fields.py`:
```
    def prepare_value(self, value):
        raise NotImplemented("This method is gone")
        if isinstance(value, AbstractMoney):
            return Decimal(value)
        return value
```

Is there a reason why we raise `NotImplemented` here instead of just removing the method? If I just remove the method, things seem to work.

Traceback:
```
Internal Server Error: /de/admin/newshop/product/375/change/
Traceback (most recent call last):
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 209, in render
    return template.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 1049, in render
    return render_value_in_context(output, context)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/template/base.py", line 1026, in render_value_in_context
    value = force_text(value)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/utils/html.py", line 381, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 148, in value
    return self.field.prepare_value(data)
  File "/home/rene/.virtualenvs/newshop/local/lib/python2.7/site-packages/shop/money/fields.py", line 43, in prepare_value
    raise NotImplemented("This method is gone")
TypeError: 'NotImplementedType' object is not callable
```

**Comment by rfleschenberg** [comment]
Fixed by PR #382.
