### ISSUE TITLE
demo does not work

### ISSUE THREAD

**Issue by sostrowsk** [awesto/django-shop#427]
I'm trying to follow the documentaion:
https://django-shop.readthedocs.io/en/latest/tutorial/intro.html#create-a-database-for-the-demo

(shopdemo)stefano@stefan:~/project/shopdemo/django-shop$ cd example
(shopdemo)stefano@stefan:~/project/shopdemo/django-shop/example$ export DJANGO_SHOP_TUTORIAL=polymorphic DJANGO_DEBUG=1
(shopdemo)stefano@stefan:~/project/shopdemo/django-shop/example$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 341, in execute
    django.setup()
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/django/**init**.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/polymorphic/models.py", line 30, in <module>
    class PolymorphicModel(six.with_metaclass(PolymorphicModelBase, models.Model)):
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/django/utils/six.py", line 808, in **new**
    return meta(name, bases, d)
  File "/home/stefano/.virtualenvs/shopdemo/local/lib/python2.7/site-packages/polymorphic/base.py", line 90, in **new**
    new_class._default_manager = user_manager._copy_to_model(new_class)
AttributeError: 'PolymorphicManager' object has no attribute '_copy_to_model'

**Comment by khchine5** [comment]
Hi @sostrowsk ,
The django-polymorphic's version  used doesn't supports Django1.10. Please , try to upgrade django-polymorphic to 1.0.1 
`pip install django-polymorphic==1.0.1`

**Comment by maltitco** [comment]
The best and fastest way to test django-shop is run by docker:

[https://github.com/awesto/django-shop#run-the-demo-using-docker](url)

**Comment by agn-7** [comment]
@khchine5 Thanks for hint
