### ISSUE TITLE
Error when I run ./manage.py compilescss

### ISSUE THREAD

**Issue by dezinfo** [awesto/django-shop#487]
```
.......................................Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/sass_processor/management/commands/compilescss.py", line 102, in handle
    self.parse_template(template_name)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/sass_processor/management/commands/compilescss.py", line 268, in parse_template
    self.compile_sass(sass_filename)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/sass_processor/management/commands/compilescss.py", line 286, in compile_sass
    content = sass.compile(**compile_kwargs)
  File "/Users/korablevop/.virtualenvs/djangoshop/lib/python3.5/site-packages/sass.py", line 517, in compile
    raise CompileError(v)
sass.CompileError: b'Error: file to import not found or unreadable: bootstrap-sass/assets/stylesheets/bootstrap\n       Current dir: /Users/korablevop/PycharmProjects/testshop/django-shop/shop/static/shop/css/\n        on line 2 of ../shop/static/shop/css/_django-shop.scss\n>> @import "bootstrap-sass/assets/stylesheets/bootstrap";\n   --------^\n'
```

**Comment by jrief** [comment]
Reading the log, it seems related to django-sass-processor, not to django-shop

did you install bootstrap-sass (npm install)?
