### ISSUE TITLE
Tutorial Issue

### ISSUE THREAD

**Issue by mightym** [awesto/django-shop#502]
Running the tutorial breaks for me on the migration part. When I `./manage.py migrate`I get the following error:

```
Unhandled exception in thread started by <function wrapper at 0x111d0f6e0>
Traceback (most recent call last):
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/test/shoptutorial/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/test/shoptutorial/Tutorial/django-shop/shop/models/__init__.py", line 2, in <module>
    from .notification import Notification, NotificationAttachment
  File "/Users/test/shoptutorial/Tutorial/django-shop/shop/models/notification.py", line 18, in <module>
    from .customer import CustomerModel
  File "/Users/test/shoptutorial/Tutorial/django-shop/shop/models/customer.py", line 23, in <module>
    from .related import ChoiceEnum
  File "/Users/test/shoptutorial/Tutorial/django-shop/shop/models/related.py", line 4, in <module>
    import enum
ImportError: No module named enum

```

**Comment by mightym** [comment]
Fixed it by manually installing `enum`. Just wanted to let you know that its missing in the deps.

**Comment by jrief** [comment]
The requirements for Python-2.7 contain the package ``enum34``.
