### ISSUE TITLE
Error unexpected keyword argument 'request' when visit your-orders page

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#548]
Error If user is not authntificate and tries visit page http://localhost:8000/info/your-orders/ :
```
Traceback (most recent call last):
  File "/home/vivazzi/.virtualenvs/django-shop-2/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/vivazzi/.virtualenvs/django-shop-2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/vivazzi/.virtualenvs/django-shop-2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vivazzi/.virtualenvs/django-shop-2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/vivazzi/.virtualenvs/django-shop-2/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/vivazzi/.virtualenvs/django-shop-2/local/lib/python2.7/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/vivazzi/projects/OTHERS/django-shop-2/django-shop/shop/rest/renderers.py", line 35, in render
    return template.render(template_context, request=request)
TypeError: render() got an unexpected keyword argument 'request'
```

**Comment by jrief** [comment]
do you use version 0.10.1?

**Comment by vivazzi** [comment]
I check version 0.10.rc4
I can check version 0.10.1

**Comment by vivazzi** [comment]
Excuse me, I miss this fix. For version 0.10.1 it work without bug. I close this issue
