### ISSUE TITLE
Error trying to login if cart has been touched beforehand.

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#593]
Adding and removing the product from cart, with cart quantity=0 also causes this.

```bash
Traceback (most recent call last):
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self.handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 234, in handle_uncaught_exception
    return handle_uncaught_exception(request, resolver, exc_info)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/exception.py", line 136, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/shop/middleware.py", line 35, in process_response
    request.customer.save(update_fields=['last_access'])
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/shop/models/customer.py", line 367, in save
    super(BaseCustomer, self).save(**kwargs)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/base.py", line 752, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'user'.
```

When this happens the cart contents are merged with the customer's cart that's trying to login.
Re-submitting the login form after this happens allows login without errors.

**Comment by jrief** [comment]
is this reproducible on one of the demo shops?

**Comment by dinoperovic** [comment]
I tried using shoptutorial example, and it's not an issue there. I'm not sure where to look for this, in my shop I am using a different login/register form and view.

**Comment by jrief** [comment]
reading your stacktrace, it doesn't seem you are using the latest version from master.

However, the problem seems to be in the middleware during the invocation of ``request.customer.save(update_fields=['last_access'])``. If you change this to ``request.customer.save()`` the error presumably does not occur.

Not sure yet, what's the reason though.

**Comment by dinoperovic** [comment]
Yes I was using 0.10.2 from pip, switching to master didn't fix it.

**Comment by jrief** [comment]
so please try by changing to ``request.customer.save()`` in "shop/middleware.py", line 35

**Comment by dinoperovic** [comment]
Now I get this:

```bash
Traceback (most recent call last):
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self.handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 234, in handle_uncaught_exception
    return handle_uncaught_exception(request, resolver, exc_info)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/exception.py", line 136, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/Users/dino/Workspace/dev/apps/django-shop/shop/middleware.py", line 35, in process_response
    request.customer.save()
  File "/Users/dino/Workspace/dev/apps/django-shop/shop/models/customer.py", line 371, in save
    super(BaseCustomer, self).save(**kwargs)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ecuga_site`.`shopit_customers`, CONSTRAINT `shopit_customers_user_id_a266fbf2_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
```

**Comment by jrief** [comment]
This means that your customer objects has no associated user object. Is this possible in your setup. Please check in the database if there are ``shopit_customers.user_id`` which is NULL.

**Comment by dinoperovic** [comment]
mysql> select * from shopit_customers;
+---------+------------+------------+----------------------------+-------+--------+
| user_id | recognized | salutation | last_access                | extra | number |
+---------+------------+------------+----------------------------+-------+--------+
|       1      |          2 |            | 2017-06-20 10:58:43.135632 | {}    |   NULL |
|      46    |          2 |            | 2017-06-20 12:43:57.508985 | {}    |   NULL |
|      94    |          0 |            | 2017-06-20 12:19:13.330052 | {}    |   NULL |
+---------+------------+------------+----------------------------+-------+--------+

I do have `user_id` for each customer in the db.

**Comment by dinoperovic** [comment]
This only happens when the cart is touched before logging in. Otherwise it works.

**Comment by dinoperovic** [comment]
@jrief I found what caused this. In building the new shop my login forms were not yet handled via ajax, but simply posting to `shop:login` which brings me to *BrowsableAPIRenderer*. That works when cart is not touched, in other case it raises the error above. 

I re-created this in shoptutorial by replacing the angular login form with a classic one, adding a product to the cart, then logging in.
