### ISSUE TITLE
Error when applying Media Configuration settings

### ISSUE THREAD

**Issue by raratiru** [awesto/django-shop#628]
I am using Python 3.4.2 on a Debian 8 Jessie box.

When applying the settings included in the [Media Configuration](https://django-shop.readthedocs.io/en/latest/reference/configuration.html#media-assets-handling) chapter, I receive the following error:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f59e03f9d90>
Traceback (most recent call last):
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/template/utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File ".virtualenvs/etisd/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".virtualenvs/etisd/lib/python3.4/site-packages/cmsplugin_cascade/sharable/admin.py", line 10, in <module>
    from cmsplugin_cascade.plugin_base import CascadePluginMixinMetaclass
  File ".virtualenvs/etisd/lib/python3.4/site-packages/cmsplugin_cascade/plugin_base.py", line 27, in <module>
    from .hide_plugins import HidePluginMixin
  File ".virtualenvs/etisd/lib/python3.4/site-packages/cmsplugin_cascade/hide_plugins.py", line 12, in <module>
    class HidePluginMixin(object):
  File ".virtualenvs/etisd/lib/python3.4/site-packages/cmsplugin_cascade/hide_plugins.py", line 17, in HidePluginMixin
    suppress_template = engines['django'].from_string('')
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File ".virtualenvs/etisd/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/templatetags/thumbnail.py", line 19, in <module>
    VALID_OPTIONS = utils.valid_processor_options()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/utils.py", line 53, in valid_processor_options
    settings.THUMBNAIL_SOURCE_GENERATORS]
TypeError: can only concatenate list (not "tuple") to list

```
When updating `django-sekizai` as per [this post](https://github.com/divio/django-cms/issues/5160), another error appears:
```


Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0d91156840>
Traceback (most recent call last):
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File ".virtualenvs/etisd/lib/python3.4/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File ".virtualenvs/etisd/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/optimize/__init__.py", line 3, in <module>
    from easy_thumbnails.optimize.post_processor import optimize_thumbnail
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/optimize/post_processor.py", line 7, in <module>
    from easy_thumbnails.optimize.conf import settings
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/optimize/conf.py", line 2, in <module>
    from easy_thumbnails.conf import Settings
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/conf.py", line 334, in <module>
    settings = Settings()
  File ".virtualenvs/etisd/lib/python3.4/site-packages/easy_thumbnails/conf.py", line 21, in __init__
    super(AppSettings, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'settings_module'
```
Commenting out all the media configuration lines, everything returns to normal.

**Comment by jrief** [comment]
You're right, ``THUMBNAIL_PROCESSORS`` should be a tuple, not a list.
Just fixed that for the next release.

**Comment by raratiru** [comment]
OK, thank you ... obvious things are rarely appreciated on time!
