### ISSUE TITLE
Error running shop.0007_notification_recipient migration using MySQL.

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#650]
Hi,

I am getting this error while trying to migrate an existing project to django-shop 0.11 - using MySQL.
This only happens trying to migrate existing data, starting a fresh database works fine.

```bash
Applying shop.0007_notification_recipient...Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 732, in _alter_field
    self.execute(self._create_fk_sql(model, new_field, "_fk_%(to_table)s_%(to_column)s"))
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ecuga_site`.`#sql-2a3_2e2`, CONSTRAINT `shop_notification_recipient_id_81184845_fk_auth_user_id` FOREIGN KEY (`recipient_id`) REFERENCES `auth_user` (`id`))')
```

**Comment by jrief** [comment]
Could you please retry with this version of the migration file:
https://github.com/awesto/django-shop/blob/releases/0.11.x/shop/migrations/0007_notification_recipient.py

there the steps have another permutation.

**Comment by dinoperovic** [comment]
Now i get this:

```bash
Applying shop.0007_notification_recipient...Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/shop/migrations/0007_notification_recipient.py", line 16, in forwards
    for row in Notification.objects.all():
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 824, in execute_sql
    sql, params = self.as_sql()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 369, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 47, in pre_sql_setup
    order_by = self.get_order_by()
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 293, in get_order_by
    field, self.query.get_meta(), default_order=asc))
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 553, in find_ordering_name
    field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 586, in _setup_joins
    pieces, opts, alias)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1402, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/Users/dino/.virtualenvs/ecuga.com/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword u'mail_to' into field. Choices are: id, mail_template, mail_template_id, name, notificationattachment, notify, recipient, transition_target
```

**Comment by jrief** [comment]
Please retry with my 2nd attempt

**Comment by dinoperovic** [comment]
Now I'm back to the first error. Breaks here:

```python
migrations.AlterField(
    model_name='notification',
    name='recipient',
    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
),
```

**Comment by jrief** [comment]
Please retry with my 3rd (28e8076) attempt.

**Comment by dinoperovic** [comment]
Yes it works now! Thanks.

**Comment by jrief** [comment]
Hugh, finally. Sorry for that and thanks for your patience.

I had to fix this model settings, because having an ``PositiveIntegerField`` holding either a pseudo foreign key, or a magic value, was a really bad idea. Therefore this change.
