### ISSUE TITLE
The error is happend when populate a database using fixtures

### ISSUE THREAD

**Issue by inzem77** [awesto/django-shop#670]
i read documentation and do as read here [https://django-shop.readthedocs.io/en/latest/tutorial/intro.html#populate-the-database-using-fixtures](url)

`(ENV) inzem@inzem-notebook: export DJANGO_SHOP_TUTORIAL=polymorphic DJANGO_DEBUG=1
(ENV) inzem@inzem-notebook: ./manage.py initialize_shop_demo
.....
Traceback (most recent call last):
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/serializers/python.py", line 179, in Deserializer
    data[field.name] = field.to_python(field_value)
  File "/home/inzem/sites/django_shop/django-shop/shop/models/fields.py", line 110, in to_python
    return self.enum_type(state)
  File "/usr/local/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/local/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'REGISTERED' is not a valid CustomerState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/serializers/json.py", line 80, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/serializers/python.py", line 181, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), field_value)
django.core.serializers.base.DeserializationError: 'REGISTERED' is not a valid CustomerState: (myshop.customer:pk=1) field_value was 'REGISTERED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/inzem/sites/django_shop/django-shop/example/myshop/management/commands/initialize_shop_demo.py", line 62, in handle
    call_command('loaddata', fixture)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 64, in handle
    self.loaddata(fixture_labels)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 104, in loaddata
    self.load_label(fixture_label)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 161, in load_label
    for obj in objects:
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/serializers/json.py", line 86, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/serializers/json.py", line 80, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/inzem/sites/django_shop/ENV/lib/python3.6/site-packages/django/core/serializers/python.py", line 181, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), field_value)
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/inzem/sites/django_shop/django-shop/workdir/polymorphic/fixtures/myshop.json': 'REGISTERED' is not a valid CustomerState: (myshop.customer:pk=1) field_value was 'REGISTERED'
`
Also it happens when i am using different DJANGO_SHOP_TUTORIAL environment variable

**Comment by jrief** [comment]
This regression has been introduced recently through this pull request https://github.com/awesto/django-shop/pull/666

In the current branch releases/0.12 is has already been fixed.
Which version of django-SHOP are you using?

**Comment by inzem77** [comment]
i cloned master branch from github and i use python 3.6

**Comment by jrief** [comment]
Please clone newest release from https://github.com/awesto/django-shop/tree/releases/0.12.x
and use Python-3.5 because we still have a minor issue with an enum type.

**Comment by jrief** [comment]
I just reverted the offending part from django-SHOP 0.11.
If you want to retry, please use Python-3.5

**Comment by inzem77** [comment]
all work in python3.5
