### ISSUE TITLE
ModuleNotFoundError: No module named X

### ISSUE THREAD

**Issue by bitsandbooks** [awesto/django-shop#712]
I'm trying to set up django-SHOP in a virtual environment on my Mac (using python 3.6.4 installed by [Homebrew](https://brew.sh)). I followed the instructions found in [the tutorial](http://django-shop.readthedocs.io/en/latest/tutorial/intro.html) and everything goes well until I try to do the first migration (cf. [§1.2.1](http://django-shop.readthedocs.io/en/latest/tutorial/intro.html#create-a-database-for-the-demo)), when I get errors like this:

    [venv] rob@carbon in ~/projects/django-shop-gh/django-shop/example
    % ./manage.py migrate
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/rob/projects/django-shop-gh/django-shop/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/Users/rob/projects/django-shop-gh/django-shop/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
        django.setup()
      File "/Users/rob/projects/django-shop-gh/django-shop/venv/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/Users/rob/projects/django-shop-gh/django-shop/venv/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/Users/rob/projects/django-shop-gh/django-shop/venv/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
        module = import_module(entry)
      File "/Users/rob/projects/django-shop-gh/django-shop/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'django_select2'

I thought that the requirements file would have installed this, but that's OK. I run `pip install django_select2` and re-run the migration:

    [venv] rob@carbon in ~/projects/django-shop-gh/django-shop/example
    % ./manage.py migrate
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      [...]
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'djng'

Unfortunately, when I try running `pip install djng`, I get an error: "No matching distribution found for djng". A bit of Googling found that this is because `django-angular` isn't installed. I install that with `pip` and re-run:

    [venv] rob@carbon in ~/projects/django-shop-gh/django-shop/example
    % ./manage.py migrate
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      [...]
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'shop_stripe'

This is getting ridiculous. How come the requirements aren't being installed automatically?

If this helps, here's the results of `pip list`:

    [venv] rob@carbon in ~/projects/django-shop-gh/django-shop/example
    % pip list
    DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
    beautifulsoup4 (4.6.0)
    bs4 (0.0.1)
    certifi (2017.11.5)
    chardet (3.0.4)
    defusedxml (0.5.0)
    Django (1.10.8)
    django-admin-sortable2 (0.6.19)
    django-allauth (0.23.0)
    django-angular (2.0.2)
    django-appconf (1.0.2)
    django-classy-tags (0.8.0)
    django-cms (3.4.5)
    django-compressor (2.2)
    django-extensions (2.0.3)
    django-filer (1.3.0)
    django-filter (1.1.0)
    django-formtools (2.1)
    django-fsm (2.6.0)
    django-fsm-admin (1.2.4)
    django-haystack (2.5.0)
    django-ipware (1.1.1)
    django-mptt (0.8.7)
    django-parler (1.8)
    django-polymorphic (1.3)
    django-post-office (3.0.3)
    django-redis-cache (1.7.1)
    django-redis-sessions (0.6.1)
    django-rest-auth (0.9.2)
    django-sass-processor (0.5.5)
    django-sekizai (0.10.0)
    django-select2 (6.0.2)
    django-shop (0.11.7, /Users/rob/projects/django-shop-gh/django-shop)
    django-treebeard (4.1.1)
    djangocms-admin-style (1.2.7)
    djangocms-bootstrap3 (0.3.1)
    djangocms-cascade (0.15.5)
    djangocms-text-ckeditor (3.4.0)
    djangorestframework (3.7.3)
    drf-haystack (1.6.1)
    easy-thumbnails (2.4.2)
    elasticsearch (1.7.0)
    hiredis (0.2.0)
    html5lib (0.9999999)
    idna (2.6)
    jsonfield (1.0.3)
    libsass (0.12.3)
    oauthlib (1.0.3)
    olefile (0.45.1)
    Pillow (4.3.0)
    pip (9.0.1)
    pygraphviz (1.3.1)
    python-dateutil (2.6.0)
    python-openid (2.2.5)
    python3-openid (3.1.0)
    pytz (2015.7)
    rcssmin (1.0.6)
    redis (2.10.6)
    requests (2.18.4)
    requests-oauthlib (0.5.0)
    rjsmin (1.0.12)
    setuptools (38.5.2)
    six (1.11.0)
    Unidecode (0.4.18)
    urllib3 (1.22)
    virtualenv (13.1.2)
    wheel (0.24.0)

**Note:** I've also installed `pygraphviz` and `django-extensions` because I want to graph the models, [like so](https://gist.github.com/perrygeo/5380196). 

EDIT: updated to fix a few minor things.

**Comment by bitsandbooks** [comment]
Never mind, I found it out. I was bashing my head against it until I found [this page](https://github.com/awesto/djangoshop-stripe) which mentioned I needed to run `pip install djangoshop-stripe`. Sorry to waste everyone's time like this.
