### ISSUE TITLE
User model (AUTH_USER_MODEL) customization impossible  

### ISSUE THREAD

**Issue by fmipsylone** [awesto/django-shop#716]
Impossible de override the AUTH_USER_MODEL.
If I do it, the migrate process fails with this stack trace:

```
Applying shop.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 91, in state_forwards
    list(self.managers),
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/state.py", line 105, in add_model
    self.reload_model(app_label, model_name)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/state.py", line 166, in reload_model
    self._reload(related_models)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/state.py", line 199, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/state.py", line 323, in render_multiple
    model.render(self)
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/migrations/state.py", line 626, in render
    body,
  File "/home/myproject/website/venv/lib/python3.6/site-packages/django/db/models/base.py", line 158, in __new__
    raise TypeError("%s cannot proxy the swapped model '%s'." % (name, base_meta.swapped))
TypeError: CustomerProxy cannot proxy the swapped model 'website_auth.User'.
```
This is due to this code in shop.0001_initial.py migration

```
if 'email_auth' in settings.INSTALLED_APPS:
   dependencies.append(('email_auth', '0001_initial'))
   customer_bases = ('email_auth.user',)
else:
   dependencies.append(('auth', '0001_initial'))
   customer_bases = ('auth.user',)
```
Unless there is an alternative I missed, that make impossible:

1.  to embed django-shop to an existing project who already override the Django User model.
2.  to customize the django user model by AUTH_USER_MODEL setting

**Comment by rfleschenberg** [comment]
Thanks for the report. I agree. In general, reusable apps should not depend on a specific `AUTH_USER_MODEL` implementation.

Sadly, I won't have time to work on a clean solution for this in the near future. Not sure if @jrief will. If you would like to make a proposal yourself, please go ahead.

**Comment by jrief** [comment]
@fmipsylone 
django-SHOP's initial intention was to give users the possibility to override AUTH_USER_MODEL.
However, sadly this has never been been tested, because everybody used the `email_auth` implementation, which is almost the same as Django's auth, but allows to use the email address.

> Unless there is an alternative I missed, that make impossible:
> 1. to embed django-shop to an existing project who already override the Django User model.

You should probably patch the migration files to fit your needs. If done generically, I will accept a pull request.

> 2. to customize the django user model by AUTH_USER_MODEL setting

Django-SHOP's philosophy is to allow users to override every model. Therefore additional fields should go to the `Customer` model rather than the `User` model. They are related through a 1:1 relation. This btw. is the recommended way to extend the User model. Read https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#extending-the-existing-user-model

The docs furthermore states: "Changing AUTH_USER_MODEL after you’ve created database tables is significantly more difficult since it affects foreign keys and many-to-many relationships, for example."

**Comment by greyhare** [comment]
I'm not in a position to create a pull request right now, but changing the else clause to this worked for me:

```python
        dependencies.append((settings.AUTH_USER_MODEL.split('.')[0], '0001_initial'))
        customer_bases = (settings.AUTH_USER_MODEL,)
```

There's probably a better way to do it with a couple extra settings.
