### ISSUE TITLE
RecursionError occuring when running ./manage.py check

### ISSUE THREAD

**Issue by mdnur89** [awesto/django-shop#754]
- Hi, I'm rather new to django and I'm learning it making an ecom store using the django-shop framework. I have edited all the models I need to initially use and switched all media with my own but when I try run ./manage.py check I get a RecursionError : maximum recursion depth exceeded while calling a Python object. I don't know how to resolve this as all methods available aren't particularly working. 

Here's my traceback...

# python manage.py check
c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\admin\product.py:109: UserWarning:
Your caching backend does not support deletion by key patterns.
Please use 'django-redis-cache', or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.ready()
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\cmsplugin_cascade\apps.py", line 21, in ready
    stylesSet = force_text(settings.CKEDITOR_SETTINGS.get('stylesSet'))
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\utils\encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\utils\functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\cmsplugin_cascade\utils.py", line 43, in format_lazy
    return format_string.format(*args, **kwargs)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\utils\functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\urls\base.py", line 60, in reverse
    app_list = resolver.app_dict[ns]
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\urls\resolvers.py", line 350, in app_dict
    self._populate()
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\urls\resolvers.py", line 290, in _populate
    for pattern in reversed(self.url_patterns):
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\urls\resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\urls\resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kaukau\AnacondaProjects\Django_projects\web_project00h\nuttyhoggz_var8\django-shop\example\myshop\urls\__init__.py", line 28, in <module>
    url(r'^', include('cms.urls')),
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\conf\urls\__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\cms\urls.py", line 16, in <module>
    if apphook_pool.get_apphooks():
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\cms\apphook_pool.py", line 75, in get_apphooks
    if app.get_urls():
  File "C:\Users\kaukau\AnacondaProjects\Django_projects\web_project00h\nuttyhoggz_var8\django-shop\example\myshop\cms_apps.py", line 28, in get_urls
    from shop.search.views import SearchView
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\search\views.py", line 16, in <module>
    from shop.views.catalog import ProductListView, AddFilterContextMixin
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\views\catalog.py", line 30, in <module>
    class ProductListView(generics.ListAPIView):
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\views\catalog.py", line 64, in ProductListView
    serializer_class = app_settings.PRODUCT_SUMMARY_SERIALIZER
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\conf.py", line 290, in __getattr__
    return getattr(self, key)
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\conf.py", line 290, in __getattr__
    return getattr(self, key)
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\conf.py", line 290, in __getattr__
    return getattr(self, key)
  [Previous line repeated 298 more times]
  File "c:\users\kaukau\anacondaprojects\django_projects\web_project00h\nuttyhoggz_var8\django-shop\shop\conf.py", line 109, in SHOP_PRODUCT_SUMMARY_SERIALIZER
    ProductSummarySerializer = import_string(pss)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "C:\Users\kaukau\Anaconda3\envs\ENV_NH_var8\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\kaukau\AnacondaProjects\Django_projects\web_project00h\nuttyhoggz_var8\django-shop\example\myshop\serializers\__init__.py", line 12, in <module>
    from myshop.search_indexes import myshop_search_index_classes
  File "C:\Users\kaukau\AnacondaProjects\Django_projects\web_project00h\nuttyhoggz_var8\django-shop\example\myshop\search_indexes.py", line 16, in <module>
    from myshop.models import *
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 174, in _get_module_lock
RecursionError: maximum recursion depth exceeded while calling a Python object
#

Please help me.

**Comment by jrief** [comment]
Are you able to start the development server?
I just tested to invoke `./manage.py check` in my local environment, and I get this. `System check identified no issues (1 silenced).`

**Comment by mdnur89** [comment]
Thank you very much sir, I had noticed I was importing with the _*_ and maybe it caused the problem as ./manage.py runserver worked aswel as ./manage.py check too.
