### ISSUE TITLE
Error in the notification menu

### ISSUE THREAD

**Issue by stilet** [awesto/django-shop#763]
TypeError at /admin/shop/notification/
__str__ returned non-string (type __proxy__)
Request Method: GET
http://127.0.0.1:8000/admin/shop/notification/
Error during template rendering
In template /home/leo/.local/share/virtualenvs/ga-JBWdJ7V9/lib/python3.6/site-packages/django/contrib/admin/templates/admin/base.html, error at line 75
__str__ returned non-string (type __proxy__)

### {% block object-tools %}{% endblock %}
`
Traceback (most recent call last):
  File "/home/leo/.local/share/virtualenvs/garantum-JBWdJ7V9/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 283, in lookup_field

    f = _get_non_gfk_field(opts, name)

  File "/home/leo/.local/share/virtualenvs/garantum-JBWdJ7V9/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 317, in _get_non_gfk_field

    field = opts.get_field(name)

  File "/home/leo/.local/share/virtualenvs/garantum-JBWdJ7V9/lib/python3.6/site-packages/django/db/models/options.py", line 619, in get_field

    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Notification has no field named 'get_recipient'
`

**Comment by jrief** [comment]
Thanks for reporting
