### ISSUE TITLE
Error with REST serializer when adding to cart

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#802]
I have a weird error and I guess it is caused by a serializer. I just don't get which one.
I used the cookiecutter as a blueprint and customized my model.
When adding my product to cart, I get this error:

`Traceback (most recent call last):
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/shop/views/cart.py", line 39, in create
    item_serializer.is_valid(raise_exception=True)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/serializers.py", line 235, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/serializers.py", line 430, in run_validation
    value = self.to_internal_value(data)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/serializers.py", line 483, in to_internal_value
    for field in fields:
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/serializers.py", line 366, in _writable_fields
    for field in self.fields.values():
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/serializers.py", line 360, in fields
    for key, value in self.get_fields().items():
  File "/Users/mohi/.pyenv/versions/3.7.7/envs/weltladen/lib/python3.7/site-packages/rest_framework/serializers.py", line 1056, in get_fields
    fields[field_name] = field_class(**field_kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoder'`

How do I debug this? I am quite lost...

**Comment by jrief** [comment]
This unfortunately isn't enough information to give any helpful hints. May it be, that there is a version mismatch of Django and DRF? Could you please send me your `pip freeze` output?
