### ISSUE TITLE
Error while do Django-SHOP Tutorial

### ISSUE THREAD

**Issue by 9Shikamaru** [awesto/django-shop#824]
On the step `pipenv run ./manage.py initialize_shop_demo` it fails with:
```(pyvir) D:\my-shop>pipenv run ./manage.py initialize_shop_demo
Traceback (most recent call last):
  File "d:\pyvir\lib\site-packages\pipenv\core.py", line 1636, in system_which
    assert c.return_code == 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kirill\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Kirill\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\pyvir\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\pyvir\lib\site-packages\pipenv\cli\command.py", line 449, in run
    command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
  File "d:\pyvir\lib\site-packages\pipenv\core.py", line 2554, in do_run
    run_fn(*run_args, **run_kwargs)
  File "d:\pyvir\lib\site-packages\pipenv\core.py", line 2475, in do_run_nt
    p = _launch_windows_subprocess(script)
  File "d:\pyvir\lib\site-packages\pipenv\core.py", line 2454, in _launch_windows_subprocess
    command = system_which(script.command)
  File "d:\pyvir\lib\site-packages\pipenv\core.py", line 1638, in system_which
    result = fallback_which(command, allow_global=True)
  File "d:\pyvir\lib\site-packages\pipenv\core.py", line 1584, in fallback_which
    result = find_python(finder, command)
  File "d:\pyvir\lib\site-packages\pipenv\utils.py", line 2196, in find_python
    result = finder.find_python_version(line)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 262, in find_python_version
    version_dict = self.parse_major(major, minor=minor, patch=patch, arch=arch)
  File "d:\pyvir\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 209, in parse_major
    int(version_dict["major"]) if version_dict.get("major") is not None else major
ValueError: invalid literal for int() with base 10: './manage.py'
```
I didn't even try to work with django-shop , just made steps from tutorial. And have no idea whats wrong. How can I fix that?

**Comment by jrief** [comment]
Doesn't seem to be related with django-SHOP itself.
A little bit of googling found this recent issue: https://github.com/pypa/pipenv/issues/4368
Please check there.

**Comment by 9Shikamaru** [comment]
@jrief, but you know, now instead of previous message nothing happens. I can't find any issue of this. Literally nothing happening. May be this can say for you smth:
```
(pyvir) D:\my-shop>pipenv run manage.py initialize_shop_demo
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore
 that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
```
Can you help please?
