### ISSUE TITLE
Dependency conflict on Django Version!

### ISSUE THREAD

**Issue by abdolhosein** [awesto/django-shop#846]
## What happened before?
Before this, the `Django-shop` through `Cookiecutter` was going to install correctly without any dependency conflict! 

## What happens now?
But now, when we're going to install `django-shop` through `cookiecutter` get following error! `Django-shop` requires `Django<3.1` but `Djangocms-cascade` needs `Django>=3.1` ! Isn't it beautiful??!
It's the problem!

The mentioned error follows:
```
ERROR: Could not find a version that matches django<3.1,<3.2,<4.0,>=1.6,>=1.8,>=1.8.0,>=2.0,>=2.1,>=2.2,>=3,>=3.1 (from -r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 10))
Tried: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.12, 1.6, 1.6, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.6.3, 1.6.3, 1.6.4, 1.6.4, 1.6.5, 1.6.5, 1.6.6, 1.6.6, 1.6.7, 1.6.7, 1.6.8, 1.6.8, 1.6.9, 1.6.9, 1.6.10, 1.6.10, 1.6.11, 1.6.11, 1.7, 1.7, 1.7.1, 1.7.1, 1.7.2, 1.7.2, 1.7.3, 1.7.3, 1.7.4, 1.7.4, 1.7.5, 1.7.5, 1.7.6, 1.7.6, 1.7.7, 1.7.7, 1.7.8, 1.7.8, 1.7.9, 1.7.9, 1.7.10, 1.7.10, 1.7.11, 1.7.11, 1.8, 1.8, 1.8.1, 1.8.1, 1.8.2, 1.8.2, 1.8.3, 1.8.3, 1.8.4, 1.8.4, 1.8.5, 1.8.5, 1.8.6, 1.8.6, 1.8.7, 1.8.7, 1.8.8, 1.8.8, 1.8.9, 1.8.9, 1.8.10, 1.8.10, 1.8.11, 1.8.11, 1.8.12, 1.8.12, 1.8.13, 1.8.13, 1.8.14, 1.8.14, 1.8.15, 1.8.15, 1.8.16, 1.8.16, 1.8.17, 1.8.17, 1.8.18, 1.8.18, 1.8.19, 1.8.19, 1.9, 1.9, 1.9.1, 1.9.1, 1.9.2, 1.9.2, 1.9.3, 1.9.3, 1.9.4, 1.9.4, 1.9.5, 1.9.5, 1.9.6, 1.9.6, 1.9.7, 1.9.7, 1.9.8, 1.9.8, 1.9.9, 1.9.9, 1.9.10, 1.9.10, 1.9.11, 1.9.11, 1.9.12, 1.9.12, 1.9.13, 1.9.13, 1.10, 1.10, 1.10.1, 1.10.1, 1.10.2, 1.10.2, 1.10.3, 1.10.3, 1.10.4, 1.10.4, 1.10.5, 1.10.5, 1.10.6, 1.10.6, 1.10.7, 1.10.7, 1.10.8, 1.10.8, 1.11, 1.11, 1.11.1, 1.11.1, 1.11.2, 1.11.2, 1.11.3, 1.11.3, 1.11.4, 1.11.4, 1.11.5, 1.11.5, 1.11.6, 1.11.6, 1.11.7, 1.11.7, 1.11.8, 1.11.8, 1.11.9, 1.11.9, 1.11.10, 1.11.10, 1.11.11, 1.11.11, 1.11.12, 1.11.12, 1.11.13, 1.11.13, 1.11.14, 1.11.14, 1.11.15, 1.11.15, 1.11.16, 1.11.16, 1.11.17, 1.11.17, 1.11.18, 1.11.18, 1.11.20, 1.11.20, 1.11.21, 1.11.21, 1.11.22, 1.11.22, 1.11.23, 1.11.23, 1.11.24, 1.11.24, 1.11.25, 1.11.25, 1.11.26, 1.11.26, 1.11.27, 1.11.27, 1.11.28, 1.11.28, 1.11.29, 1.11.29, 2.0, 2.0, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.0.4, 2.0.4, 2.0.5, 2.0.5, 2.0.6, 2.0.6, 2.0.7, 2.0.7, 2.0.8, 2.0.8, 2.0.9, 2.0.9, 2.0.10, 2.0.10, 2.0.12, 2.0.12, 2.0.13, 2.0.13, 2.1, 2.1, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.1.4, 2.1.4, 2.1.5, 2.1.5, 2.1.7, 2.1.7, 2.1.8, 2.1.8, 2.1.9, 2.1.9, 2.1.10, 2.1.10, 2.1.11, 2.1.11, 2.1.12, 2.1.12, 2.1.13, 2.1.13, 2.1.14, 2.1.14, 2.1.15, 2.1.15, 2.2, 2.2, 2.2.1, 2.2.1, 2.2.2, 2.2.2, 2.2.3, 2.2.3, 2.2.4, 2.2.4, 2.2.5, 2.2.5, 2.2.6, 2.2.6, 2.2.7, 2.2.7, 2.2.8, 2.2.8, 2.2.9, 2.2.9, 2.2.10, 2.2.10, 2.2.11, 2.2.11, 2.2.12, 2.2.12, 2.2.13, 2.2.13, 2.2.14, 2.2.14, 2.2.15, 2.2.15, 2.2.16, 2.2.16, 2.2.17, 2.2.17, 2.2.18, 2.2.18, 3.0, 3.0, 3.0.1, 3.0.1, 3.0.2, 3.0.2, 3.0.3, 3.0.3, 3.0.4, 3.0.4, 3.0.5, 3.0.5, 3.0.6, 3.0.6, 3.0.7, 3.0.7, 3.0.8, 3.0.8, 3.0.9, 3.0.9, 3.0.10, 3.0.10, 3.0.11, 3.0.11, 3.0.12, 3.0.12, 3.1, 3.1, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.1.4, 3.1.4, 3.1.5, 3.1.5, 3.1.6, 3.1.6
Skipped pre-versions: 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.10a1, 1.10a1, 1.10b1, 1.10b1, 1.10rc1, 1.10rc1, 1.11a1, 1.11b1, 1.11rc1, 1.11rc1, 2.0a1, 2.0b1, 2.0rc1, 2.1a1, 2.1b1, 2.1rc1, 2.2a1, 2.2a1, 2.2b1, 2.2b1, 2.2rc1, 2.2rc1, 3.0a1, 3.0a1, 3.0b1, 3.0b1, 3.0rc1, 3.0rc1, 3.1a1, 3.1a1, 3.1b1, 3.1b1, 3.1rc1, 3.1rc1, 3.2a1, 3.2a1
There are incompatible versions in the resolved dependencies:
  django>=3 (from -r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 10))
  django<3.1,>=2.1 (from django-shop==1.2.4->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 5))
  django<3.2,>=1.8 (from django-admin-sortable2==0.7.8->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 36))
  django<4.0,>=2.2 (from django-filer==2.0.2->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 22))
  django>=1.6 (from django-fsm-admin==1.2.4->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 27))
  django>=1.8.0 (from django-rest-auth==0.9.5->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 24))
  django>=2.0 (from django-allauth==0.44.0->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 14))
  django>=2.1 (from django-angular==2.3->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 7))
  django>=2.1 (from django-polymorphic==3.0.0->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 16))
  django>=2.2 (from django-cms==3.8.0->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 32))
  django>=2.2 (from django-filter==2.4.0->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 31))
  django>=2.2 (from django-phonenumber-field==5.0.0->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 38))
  django>=2.2 (from django-post-office==3.5.3->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 29))
  django>=2.2 (from django-select2==7.6.1->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 37))
  django>=2.2 (from djangorestframework==3.12.2->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 21))
  django>=3.1 (from djangocms-cascade==2.0->-r /var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/pipenvcp8s45vfrequirements/pipenv-yx64xan9-constraints.txt (line 25))

Traceback (most recent call last):
  File "/var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/tmprd4iaypf.py", line 229, in <module>
    main()
  File "/var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/tmprd4iaypf.py", line 217, in main
    pipenv_to_requirements()
  File "/var/folders/gh/psm7s6d116q_gblnk_vlhst40000gn/T/tmprd4iaypf.py", line 159, in pipenv_to_requirements
    ret = subprocess.check_output(['pipenv', 'lock', '--requirements'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pipenv', 'lock', '--requirements']' returned non-zero exit status 1.
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

## Steps to reproduce
Just install `django-shop` through `cookiecutter`!(Something like this: `cookiecutter https://github.com/awesto/cookiecutter-django-shop`)

**Comment by ay0000** [comment]
Adding a `--skip-lock` to the `pipenv --sequential` command worked for me, if you're using Django 3.0.12.

**Comment by jhonvidal** [comment]
I have the same problem, I am waiting for a new update to correct this detail.

**Comment by alex-eri** [comment]
`djangocms-cascade = ">=1.3.1,<2.0.0"` in  Pipfile for quick fix

**Comment by Josephine-Marie** [comment]
there is another one: the pipfile that comes with cookiecutter installs django-treebeard 4.5.1 
If you try to initialize_shop_demo then for example, the example pages do not load 
https://forum.djangoproject.com/t/django-cms-publish-page-changes-nodealreadysaved/6821
if you install treebeard 4.4 before installing the dependencies/pipfile, everything works

**Comment by ay0000** [comment]
@Josephine-Marie,
See here:

https://github.com/awesto/cookiecutter-django-shop/issues/41#issuecomment-780184052
