### ISSUE TITLE
OperationalError at / no such table: cms_urlconfrevision

### ISSUE THREAD

**Issue by OsamaDaghestani** [awesto/django-shop#854]
hello i really like your code but i am getting this error OperationalError at / no such table: cms_urlconfrevision and my migrations are not saving i mean no matter how many times i migrate i am getting the same output and while i am migrating it keeps migrating the same thing over and over again thank you in advance

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/products/

Django Version: 3.0.14
Python Version: 3.6.8
Installed Applications:
['django.contrib.auth',
 'email_auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'jsonfield',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_auth',
 'django_fsm',
 'fsm_admin',
 'filer',
 'easy_thumbnails',
 'treebeard',
 'menus',
 'sekizai',
 'cms',
 'adminsortable2',
 'djangocms_text_ckeditor',
 'django_select2',
 'cmsplugin_cascade',
 'cmsplugin_cascade.clipboard',
 'cmsplugin_cascade.extra_fields',
 'cmsplugin_cascade.icon',
 'cmsplugin_cascade.sharable',
 'cmsplugin_cascade.segmentation',
 'post_office',
 'shop',
 'testshop']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'shop.middleware.CustomerMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'cms.middleware.language.LanguageCookieMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.utils.ApphookReloadMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware']



Traceback (most recent call last):
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such table: cms_urlconfrevision) was the direct cause of the following exception:
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\cms\middleware\utils.py", line 14, in process_request
    apphook_reload.ensure_urlconf_is_up_to_date()
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\cms\utils\apphook_reload.py", line 25, in ensure_urlconf_is_up_to_date
    global_revision = get_global_revision()
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\cms\utils\apphook_reload.py", line 68, in get_global_revision
    revision=str(uuid.uuid4()))
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\cms\models\apphooks_reload.py", line 31, in get_or_create_revision
    pk=1, defaults=dict(revision=revision))
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\models\sql\compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\daghe\.virtualenvs\django-shop-master\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /products/
Exception Value: no such table: cms_urlconfrevision
```

**Comment by jrief** [comment]
I have no idea why your installation can't find your DB table `cms_urlconfrevision`. This presumably has to do with your installation od django-CMS. It however is unrelated to django-SHOP.
